### ISSUE TITLE
Why are you not engaging with Describo Profiles?

### ISSUE THREAD

**Issue by marcolarosa** [Language-Research-Technology/ro-crate-editor-profiles#3]
@ptsefton

It is perfectly reasonable that you would want to extend profiles beyond their current state. However, rather than creating yet another copy of my work, why not engage with Describo Profiles and operate in the mainline that is being used by others around the world? 

You and your team have not raised any issues or feature requests in that repository. Nor have you engaged with it in any way. Describo Profiles has a mechanism for publishing domain specific profiles for use by various tools and it seems that you are just copying this work in order to not use Describo Profiles.

As it happens, I have to make changes to profiles as well and this risks them diverging which is not good for the community or the tooling.

I'm all for different implementations of the tooling. But creating yet another version of profiles (as you've noted) is not a sensible path forward.

Please reconsider your decision and engage with Describo Profiles. If you are not satisfied that your requirements are being met, then of course go ahead and do your own thing.

**Comment by ptsefton** [comment]
I am closing this issue as this is not the right place for this discussion.

**Comment by marcolarosa** [comment]
Please explain why.

**Comment by ptsefton** [comment]
I am closing this issue as this is not the right place for this discussion.

**Comment by marcolarosa** [comment]
This is not communication. You are deciding unilaterally that this conversation will not happen without offering a reason why or how it might move forward. Saying this is "not the right place" and not addressing any of my questions or comments is not how to run a community.

**Comment by marcolarosa** [comment]
I note your update to the README ("Describo maintainers aware of our initial implementation and we can discuss whether we can harmonize our approaches) but this still doesn't justify your approach or resolve why you took this path as a first option.

**Comment by ptsefton** [comment]
I am closing this issue as noted above.
